ejemplos2/ejemplo2/proyectoUno/administrativo/urls.py
"""
    Manejo de urls para la aplicación
    administrativo
"""
from django.urls import path
# se importa las vistas de la aplicación
from . import views


urlpatterns = [
        path('', views.index, name='index'),
        path('estudiante/<int:id>', views.obtener_estudiante, 
            name='obtener_estudiante'),
        path('crear/estudiante', views.crear_estudiante, 
            name='crear_estudiante'),
        path('editar_estudiante/<int:id>', views.editar_estudiante, 
            name='editar_estudiante'),
        path('eliminar/estudiante/<int:id>', views.eliminar_estudiante, 
            name='eliminar_estudiante'),
        # numeros telefonicos
        path('crear/numero/telefonico', views.crear_numero_telefonico, 
            name='crear_numero_telefonico'),
        path('editar/numero/telefonico/<int:id>', views.editar_numero_telefonico, 
            name='editar_numero_telefonico'),
        path('crear/numero/telefonico/estudiante/<int:id>', 
            views.crear_numero_telefonico_estudiante, 
            name='crear_numero_telefonico_estudiante'),
 ]

ejemplos2/ejemplo2/proyectoUno/proyectoUno/urls.py
from django.contrib import admin
from django.urls import path, include
# from django.conf.urls import include, url

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('administrativo.urls')),
]

ejemplos2/ejemplo2/proyectoUno/administrativo/models.py
from django.db import models

# Create your models here.

class Estudiante(models.Model):
    nombre = models.CharField(max_length=30)
    apellido = models.CharField(max_length=30)
    cedula = models.CharField(max_length=30, unique=True)
    correo = models.EmailField()

    def __str__(self):
        return "%s %s %s %s" % (self.nombre,
                self.apellido,
                self.cedula,
                self.correo)

class NumeroTelefonico(models.Model):
    telefono = models.CharField(max_length=100)
    tipo = models.CharField(max_length=100)
    estudiante = models.ForeignKey(Estudiante, on_delete=models.CASCADE,
            related_name="numeros_telefonicos")

    def __str__(self):
        return "%s %s" % (self.telefono, self.tipo)

ejemplos2/ejemplo2/proyectoUno/administrativo/forms.py
from django.forms import ModelForm
from django.utils.translation import gettext_lazy as _
from django import forms

from administrativo.models import Estudiante, \
        NumeroTelefonico

class EstudianteForm(ModelForm):
    class Meta:
        model = Estudiante
        fields = ['nombre', 'apellido', 'cedula', 'correo']
        labels = {
            'nombre': _('Ingrese nombre por favor'),
            'apellido': _('Ingrese apellido por favor'),
            'cedula': _('Ingrese cédula por favor'),
            'correo': _('Ingrese correo por favor'),
        }


    def clean_nombre(self):
        valor = self.cleaned_data['nombre']
        num_palabras = len(valor.split())

        if num_palabras < 2:
            raise forms.ValidationError("Ingrese dos nombre por favor")
        return valor

    def clean_apellido(self):
        valor = self.cleaned_data['apellido']
        num_palabras = len(valor.split())

        if num_palabras < 2:
            raise forms.ValidationError("Ingrese dos apellidos por favor")
        return valor

    def clean_cedula(self):
        valor = self.cleaned_data['cedula']
        if len(valor) != 10:
            raise forms.ValidationError("Ingrese cédula con 10 dígitos")
        return valor

    def clean_correo(self):
        valor = self.cleaned_data['correo']
        if "@" not in valor or "utpl.edu.ec" not in valor:
            raise forms.ValidationError("Ingrese correo válido para la Universidad")
        return valor


class NumeroTelefonicoForm(ModelForm):
    class Meta:
        model = NumeroTelefonico
        fields = ['telefono', 'tipo', 'estudiante']


class NumeroTelefonicoEstudianteForm(ModelForm):

    def __init__(self, estudiante, *args, **kwargs):
        super(NumeroTelefonicoEstudianteForm, self).__init__(*args, **kwargs)
        self.initial['estudiante'] = estudiante
        self.fields["estudiante"].widget = forms.widgets.HiddenInput()
        print(estudiante)

    class Meta:
        model = NumeroTelefonico
        fields = ['telefono', 'tipo', 'estudiante']

ejemplos2/ejemplo2/proyectoUno/administrativo/templates/crearEstudiante_2.html
{% extends "master.html" %}

{% block content %}
<h2>Crear Estudiante</h3>

<form action="" method="post">

  {% csrf_token %}

  {{ formulario.non_field_errors }}
  <div class="fieldWrapper">
    {{ formulario.nombre.errors }}
    <label for="{{ formulario.nombre.id_for_label }}">Ingrese Nombre:</label>
    {{ formulario.nombre }}
  </div>
  <br>
  <div class="fieldWrapper">
    {{ formulario.apellido.errors }}
    <label for="{{ formulario.apellido.id_for_label }}">Ingrese Apellido:</label>
    {{ formulario.apellido }}
  </div>
  <br>
  <div class="fieldWrapper">
    {{ formulario.cedula.errors }}
    <label for="{{ formulario.cedula.id_for_label }}">Ingrese Cédula:</label>
    {{ formulario.cedula }}
  </div>
  <br>
  <div class="fieldWrapper">
    {{ formulario.correo.errors }}
    <label for="{{ formulario.correo.id_for_label }}">Ingrese Correo:</label>
    {{ formulario.correo }}
  </div>

  <p><input type='submit' value='Agregar'/></p>

</form>

{% endblock %}

ejemplos2/ejemplo2/proyectoUno/administrativo/templates/crearEstudiante_3.html
{% extends "master.html" %}

{% block content %}
<h2>Crear Estudiante</h3>

<form action="" method="post">

  {% csrf_token %}

<div class='wrapper-dos-columnas'>
  <div class='row'>
    <div class='column'>
      <div class='izquierda-column'>
        <br>
        <div class="fieldWrapper">
          {{ formulario.nombre.errors }}
          <label for="{{ formulario.nombre.id_for_label }}">Ingrese Nombre:</label>
          {{ formulario.nombre }}
        </div>
        <br>
        <br>
        {{ formulario.non_field_errors }}
        <div class="fieldWrapper">
          {{ formulario.apellido.errors }}
          <label for="{{ formulario.apellido.id_for_label }}">Ingrese Apellido:</label>
          {{ formulario.apellido }}
        </div>
        <br>
        <div><input type='submit' value='Agregar'/></div>
      </div>
    </div>
    <div class='column'>
      <div class='derecha-column'>
        <br>
        <div class="fieldWrapper">
          {{ formulario.cedula.errors }}
          <label for="{{ formulario.cedula.id_for_label }}">Ingrese Cédula:</label>
          {{ formulario.cedula }}
        </div>
        <br>
        <br>
        <div class="fieldWrapper">
          {{ formulario.correo.errors }}
          <label for="{{ formulario.correo.id_for_label }}">Ingrese Correo:</label>
          {{ formulario.correo }}
        </div>
      </div>
    </div>
  </div>
</div>

</form>
<br>
{% endblock %}

ejemplos2/ejemplo2/proyectoUno/administrativo/templates/crearNumeroTelefonico.html
{% extends "master.html" %}

{% block content %}

<h2>Crear Número Telefónico</h3>

<form action="" method="post">

  {% csrf_token %}

  {{formulario.as_p}}

  <p><input type='submit' value='Agregar'/></p>
</form>
{% endblock %}

ejemplos2/ejemplo2/proyectoUno/administrativo/templates/crearNumeroTelefonicoEstudiante.html
{% extends "master.html" %}

{% block content %}
<h2>Crear Número Telefónico para {{estudiante}}</h3>

<form action="" method="post">
  {% csrf_token %}
  {{formulario.as_p}}
  <p><input type='submit' value='Agregar'/></p>
</form>

{% endblock %}

ejemplos2/ejemplo2/proyectoUno/administrativo/templates/editarEstudiante.html
{% extends "master.html" %}

{% block content %}
<h2>Editar Estudiante</h3>

<form action="" method="post">
  {% csrf_token %}
  {{formulario.as_p}}
  <p><input type='submit' value='Actualizar'/></p>
</form>

{% endblock %}

ejemplos2/ejemplo2/proyectoUno/administrativo/templates/index.html
{% extends "master.html" %}

{% block title %}
  Listado de Estudiantes | {{ block.super }}
{% endblock %}

{% block content %}
<h3>Número de estudiantes {{ numero_estudiantes }}</h3>

<table id="tabla_datos">

  <thead>
    <tr>
      <th>Estudiante</th>
      <th>Cedula</th>
      <th>Correo</th>
      <th>Numeros Telefónico </th>
      <th>Opciones</th>
    </tr>
  </thead>

  {% for e in estudiantes %}
  <tr>
    <td> {{e.nombre}} {{e.apellido}}</td>
    <td> {{e.cedula}}</td>
    <td> {{e.correo}}</td>
    <td>
      <ul>
        {% for t in e.numeros_telefonicos.all %}
          <li>
            <span>{{t.telefono}} - {{t.tipo}} - [<a href="{% url 'editar_numero_telefonico' t.id %}">editar</a>] </span>
          </li>
        {% endfor %}
      </ul>
        [<a href="{% url 'crear_numero_telefonico_estudiante' e.id%}">+Teléfono</a>]
    </td>
    <td> <a href="{% url 'obtener_estudiante' e.id %}">ver</a> <br>
      <a href="{% url 'editar_estudiante' e.id %}">editar</a> <br>
      <a href="{% url 'eliminar_estudiante' e.id %}"
      onclick="return confirm('¿Está seguro de la eliminación?')" >
      eliminar</a>
    </td>

  </tr>
  {% endfor %}
</table>

<script type="text/javascript">
  $(document).ready( function () {
    $('#tabla_datos').DataTable();
  });
</script>

{% endblock %}

ejemplos2/ejemplo2/proyectoUno/administrativo/templates/listadoEstudiantesDos.html
<h2>Listado de Estudiantes</h3>
<h3>Número de estudiantes {{ numero_estudiantes }}</h3>

{% for e in estudiantes %}
    
  {{e}}<br/>
  <ul>
  {% for numero in e.numerotelefonico_set.all%}
      <li>
          Número telefónico {{numero}}<br/>
      </li>
  {% endfor %}
  </ul>
  <br/>
{% endfor %}

ejemplos2/ejemplo2/proyectoUno/administrativo/templates/master.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/estilos.css' %}">

    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.25/css/jquery.dataTables.min.css">
    <script type="text/javascript" src="https://code.jquery.com/jquery-3.5.1.js"></script>
    <script type="text/javascript" src="https://cdn.datatables.net/1.10.25/js/jquery.dataTables.min.js"></script>

    <title>
      {% block title %}
      Aplicación Administración
      {% endblock %}
    </title>
  </head>
  <body>
  <header>
    <img src="{% static 'images/logo.png' %}" height="10%" width="10%" alt="My image">
    <h1>Aplicación Administración </h1>
    <nav class="top_menu">
      <ul>
        <li><a href="{% url 'index' %}">inicio</a></li>
        <li><a href="{% url 'crear_estudiante' %}">agregar estudiante</a></li>
        <li><a href="{% url 'crear_numero_telefonico' %}">agregar telefono</a></li>
      </ul>
    </nav>
  </header>
  <section>
      {% block content %}
        <span>Bienvenidos:</span>
      {% endblock %}
  </section>
  {% include 'footer.html' %}
  </body>
</html>

ejemplos2/ejemplo2/proyectoUno/administrativo/templates/obtener_estudiante.html
{% extends "master.html" %}

{% block content %}

<h3>Datos de estudiante</h3>

<p><b>Nombre:</b>{{estudiante.nombre}}</p>
<p><b>Apellido:</b>{{estudiante.apellido}}</p>
<p><b>Cédula:</b>{{estudiante.cedula}}</p>
<p><b>Correo:</b>{{estudiante.correo}}</p>

<br/>
{% endblock %}